"""Simply exists to convert JSON file to an escaped string that can be referenced as an elisp variable"""

import datetime
import json
import pathlib


def main(builtinsFile=pathlib.Path("src/builtins.json")):
    builtins: str = ""  # escaped JSON string
    with open(builtinsFile) as f:
        d = json.load(f)
        builtins = json.dumps(json.dumps(d))
    f.close()
    cicodeBuiltinsContents: str = f""";; cicode-mode-builtins.el
;; WARN: DO NOT EDIT THIS FILE
;; This file is autogenerated by `convert-json-to-elisp-string.py`
;; Last created on {datetime.datetime.now().strftime("%d/%m/%y %H:%M")}

(defvar cicode-mode-json-builtins-str {builtins}
  "JSON String of builtin functions")

(provide 'cicode-mode-builtins)

;;; cicode-mode-builtins.el ends here
"""
    with open("cicode-mode-builtins.el", "w") as builtinsFileWriter:
        builtinsFileWriter.write(cicodeBuiltinsContents)
    builtinsFileWriter.close()


if __name__ == "__main__":
    main()
